# .github/workflows/update-activity.yml
name: Update Activity

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updated with recent activity'
          MAX_LINES: 5
