# .github/workflows/update-readme.yml
name: 'Update README'

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Update README with recent activity'
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: '.github/recent-activity.config.yml'

  update-stats:
    name: 'Update GitHub Stats'
    runs-on: ubuntu-latest
    needs: recent-activity
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Generate GitHub Stats'
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ParrotXray
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei

          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
